# -*- coding: utf-8 -*-
"""KNN_Model_SMOTETomek.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aarqhS8qizBvWMjfBXBDacXpEqBjVSz1
"""

import numpy as np
import pandas as pd
import sklearn
import scipy
from sklearn.metrics import classification_report,accuracy_score
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from pylab import rcParams
#from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn import preprocessing
data = pd.read_csv(r'/home/supriya/pathcontext/vectorization_work/CDS_vectorization_v1.csv',dtype={'Error_Label':object} )
print(data)
#data.head()

# split labels and return new dataframe
#Create independent and Dependent Features
#data=split_label(data)
def split_label_dict(df):
    # Change 'label' to whatever naming used in the original DataFrame.
    temp_df = df['Error_Label'].str.split("", n = -1, expand = True)
    for i in range(1, 19):
        df[f'l{1}'] = temp_df[1]
        df[f'l{1}'] = pd.to_numeric(df[f'l{1}'])
    return df

newdata=split_label_dict(data)
#print(newdata)
#Create independent and Dependent Features
columns = newdata.columns.tolist()
# Filter the columns to remove data we do not want 
columns = [c for c in columns if c not in ["l1"]]
# Store the variable we are predicting 
target = "l1"
# Define a random state 
state = np.random.RandomState(69)
X = newdata[columns]
Y = newdata[target]
# Print the shapes of X & Y
print(X.shape)
print(Y)

from sklearn.model_selection import train_test_split

X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=69)

# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
smk = SMOTETomek()
X_res,y_res=smk.fit_sample(X_train.astype('float'),y_train)
print(X_res.shape,y_res.shape)
#print(X_res)
#print(y_res)


from sklearn.ensemble import RandomForestClassifier
# Fitting the classifier into the Training set
classifier = RandomForestClassifier(n_estimators = 100)
model=classifier.fit(X_res,y_res)
# Predicting the test set results
y_predict = classifier.predict(X_test)
print(accuracy_score(y_test,y_predict))
pd.crosstab(y_test,y_predict)

import pickle
# Save History as Pickle

filename = '/home/supriya/pathcontext/vectorization_work/Random_Forest/SMOTETomek_results/l1RFTomek.pickle'
with open(filename, 'wb') as fh:
    pickle.dump(model, fh)

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score
print(classification_report(y_test,y_predict))
print(accuracy_score(y_test,y_predict))

from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score 
from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score
import pickle
results=classification_report(y_test,y_predict)
macro=f1_score(y_test, y_predict, average='macro')
micro=f1_score(y_test, y_predict, average='micro')
weighted=f1_score(y_test, y_predict, average='weighted')
avg=f1_score(y_test, y_predict, average=None)
#accuracy_score=accuracy_score(y_test,y_predict)
cm = confusion_matrix(y_test, y_predict)
roc=roc_auc_score(y_test,y_predict)

print(cm)
print(results) 
print(roc)
#print(accuracy_score)

# Save Results as Pickle
filename = '/home/supriya/pathcontext/vectorization_work/Random_Forest/SMOTETomek_results/l1RFTomek_results.txt'
with open(filename, 'a') as fh:
    fh.write(str(results)+"\n" +"ROC_ACCuracy:  "+str(roc) +"\n"+"Confusion_Matrix"+"\n"+str(cm)+"\n"+"macro_f1 "+str(macro)+"\n"+"micro_f1:"+str(micro)+
"\n"+"weighted_f1:"+str(weighted)+"\n"+"avg_f1:"+str(avg))